aggregatekeylinks agg complete offline txs fix
nemtech/symbol-cli pull request #367
Opened 2021-03-25 21:06 UTC by yilmazbahadir

fixes https://github.com/nemtech/symbol-cli/issues/366

2021-03-25 21:22 UTC, rg911 approved these changes

2021-03-26 07:23 UTC, segfaultxavi requested changes
Some minor text changes!

2021-03-26 07:23 UTC, segfaultxavi commented on src/resolvers/cosignature.resolver.ts
> +            altText ? altText : 'Enter the cosignature json array(wrapped by square brackets) - press enter to skip:',
```suggestion
            altText ? altText : 'Cosignature JSON array in square brackets (Enter to skip):',
```

2021-03-26 07:23 UTC, segfaultxavi commented on src/resolvers/cosignature.resolver.ts
> +            console.log('Unexpected format! Please make sure the input is wrapped by square brackets []');
```suggestion
            console.log('Unexpected format! Please make sure the input is a valid JSON array. It must be wrapped in square brackets [].');
```

2021-03-26 09:33 UTC, segfaultxavi approved these changes

2021-03-26 09:41 UTC, rg911 approved these changes

2021-03-26 10:01 UTC, merged